/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_aserbao_androidcustomcamera_utils_VoiceUtils */

#ifndef _Included_com_aserbao_androidcustomcamera_utils_VoiceUtils
#define _Included_com_aserbao_androidcustomcamera_utils_VoiceUtils
#ifdef __cplusplus
extern "C" {
#endif
#undef com_aserbao_androidcustomcamera_utils_VoiceUtils_MODE_NORMAL
#define com_aserbao_androidcustomcamera_utils_VoiceUtils_MODE_NORMAL 0L
#undef com_aserbao_androidcustomcamera_utils_VoiceUtils_MODE_LUOLI
#define com_aserbao_androidcustomcamera_utils_VoiceUtils_MODE_LUOLI 1L
#undef com_aserbao_androidcustomcamera_utils_VoiceUtils_MODE_DASHU
#define com_aserbao_androidcustomcamera_utils_VoiceUtils_MODE_DASHU 2L
#undef com_aserbao_androidcustomcamera_utils_VoiceUtils_MODE_JINGSONG
#define com_aserbao_androidcustomcamera_utils_VoiceUtils_MODE_JINGSONG 3L
#undef com_aserbao_androidcustomcamera_utils_VoiceUtils_MODE_GAOGUAI
#define com_aserbao_androidcustomcamera_utils_VoiceUtils_MODE_GAOGUAI 4L
#undef com_aserbao_androidcustomcamera_utils_VoiceUtils_MODE_KONGLING
#define com_aserbao_androidcustomcamera_utils_VoiceUtils_MODE_KONGLING 5L

/*
 * Class:     com_aserbao_androidcustomcamera_utils_VoiceUtils
 * Method:    fix
 * Signature: (Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_com_aserbao_androidcustomcamera_utils_VoiceUtils_fix
  (JNIEnv *, jclass, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
